### ISSUE TITLE
new lines in commentMode "raw"

### ISSUE THREAD

**Issue by LJMP** [EPIVISION/vscode-file-header#1]
"powerHeader.commentMode": "raw" puts literal `\n`?
should be an actual new line replace instead there?
https://github.com/EPIVISION/vscode-file-header/blob/f7469cf0005bc2ded275d1a804bc9aacbe9ad389/src/main.ts#L148

**Comment by EPIVISION** [comment]
thanks for reporting 👍 fixed in 1.0.8
