### ISSUE TITLE
`filename` field does not change with filename change

### ISSUE THREAD

**Issue by thep0y** [EPIVISION/vscode-file-header#10]
If I rename a file named `main.go` to `test.go`, the `filename` field in the file header is still `main.go`.

**Comment by 5P5** [comment]
I assume you use the `$TM_FILENAME` vscode snippet in your "powerHeader.template" to get the filename.
This will only be interpreted on a new header insert.
There is no general method to update the filename in a header, as the existence of this string depends solely on your individual template.
Maybe I figure out a clever way to do this via "powerHeader.update.content".
