### ISSUE TITLE
Modified can't update automatically

### ISSUE THREAD

**Issue by thep0y** [EPIVISION/vscode-file-header#3]
settings.json:
```json
    "powerHeader.variables": [
        "!date!=new Date(+new Date(new Date().toJSON(new Date().getTime()))+ 8 * 3600 * 1000).toISOString().replace(/T/g,' ').replace(/\\.[\\d]{3}Z/,'')"
    ],
    "[python]": {
        "powerHeader.autoInsert.enable": true,
        "powerHeader.autoInsert.allow": "always",
        "powerHeader.commentMode": "raw",
        "powerHeader.template": "#!/usr/bin/env python\\n# -*- coding: utf-8 -*-\\n# @Author: thepoy\\n# @Email: thepoy@163.com\\n# @File Name: $TM_FILENAME (c) $CURRENT_YEAR\\n# @Created:  !date!\\n# @Modified: !date!\\n"
    }
```

test file:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: thepoy
# @Email: thepoy@163.com
# @File Name: test2.py (c) 2020
# @Created:  2020-11-21 19:28:07
# @Modified: !date!

if __name__ == "__main__":
    print('Hello World!')
```

After creating the new file, it has been saved many times and the `Modified` cannot be updated automatically.

**Comment by EPIVISION** [comment]
Hello,
I tested your example. Very thing is correct, you just need one more setting:

In _settings.json_ you need to enable the update functionality 
use `"powerHeader.update.enable": "manual"` to update with shortcut (<kbd>Ctrl+Alt+H</kbd>)
or `"powerHeader.update.enable": "save"` to automatically before you save <kbd>Ctrl+S</kbd> the file
###### Please also note [this  caveat](https://github.com/EPIVISION/vscode-file-header/blob/master/README.md#known-issues)

Add it e.g. to the python section like this😉
```jsonc
    "[python]": {
        "powerHeader.autoInsert.enable": true,
        "powerHeader.autoInsert.allow": "always",
        "powerHeader.commentMode": "raw",
        "powerHeader.template": "#!/usr/bin/env python\\n# -*- coding: utf-8 -*-\\n# @Author: thepoy\\n# @Email: thepoy@163.com\\n# @File Name: $TM_FILENAME (c) $CURRENT_YEAR\\n# @Created:  !date!\\n# @Modified: !date!\\n"
,"powerHeader.update.enable": "manual"
    }
```

**Comment by thep0y** [comment]
> Hello,
> I tested your example. Everything is correct, you just need one more setting:
> 
> In _settings.json_ you need to enable the update functionality
> use `"powerHeader.update.enable": "manual"` to update with shortcut (Ctrl+Alt+H)
> or `"powerHeader.update.enable": "save"` to automatically do update on saving the file Ctrl+S
> 
> ###### Please also note [this caveat](https://github.com/EPIVISION/vscode-file-header/blob/master/README.md#known-issues)
> Add it e.g. to the python section like this😉
> 
> ```js
>     "[python]": {
>         "powerHeader.autoInsert.enable": true,
>         "powerHeader.autoInsert.allow": "always",
>         "powerHeader.commentMode": "raw",
>         "powerHeader.template": "#!/usr/bin/env python\\n# -*- coding: utf-8 -*-\\n# @Author: thepoy\\n# @Email: thepoy@163.com\\n# @File Name: $TM_FILENAME (c) $CURRENT_YEAR\\n# @Created:  !date!\\n# @Modified: !date!\\n"
> ,"powerHeader.update.enable": "manual"
>     }
> ```

It is worked now, thank you.
